name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ajith
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        run: |
          python manage.py migrate

      - name: Run Unit Tests for Shop App
        run: |
          python manage.py test shop.tests

  # Deployment Job (Currently Commented Out)
  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10'

  #     - name: Install Dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Deploy to Production Server
  #       env:
  #         HOST: ${{ secrets.SERVER_HOST }}
  #         USER: ${{ secrets.SERVER_USER }}
  #         SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #       run: |
  #         echo "$SSH_KEY" > deploy_key.pem
  #         chmod 600 deploy_key.pem
  #         ssh -o StrictHostKeyChecking=no -i deploy_key.pem $USER@$HOST << 'EOF'
  #         cd /path/to/your/project
  #         git pull origin main
  #         source venv/bin/activate
  #         pip install -r requirements.txt
  #         python manage.py migrate
  #         python manage.py collectstatic --noinput
  #         sudo systemctl restart gunicorn
  #         EOF
  #         rm deploy_key.pem
